### ISSUE TITLE
Active Development?

### ISSUE THREAD

**Issue by aptonline** [tjohnman/Obsession#45]
Hi, Thanks for taking the time to create this app, a modern Mac app for Hotline is sorely missing and this development fills a much needed gap.

I've noticed that build hasn't been updated in some time, is development still happening?  I'd be interested in contributing where I can.

The Hotline community is still active, especially with the Mobius server (https://github.com/jhalter/mobius) which can run on modern hardware.

**Comment by tjohnman** [comment]
Hey there. Ironically, I initially made this because there wasn't a modern Windows application for Hotline that satisfied me. I wouldn't say development is very active, but I'm willing to take a look at bugs if people are using it at all.

Please, feel free to report things and make pull requests if you can.
